# GitHub Action Workflow enforcing our code style.

name: Lint

# Trigger the workflow on both push (to the main repository)
# and pull requests (against the main repository, but from any repo).
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    env:
      # Set an environment variable to select pip's cache directory for us to actually cache between runs.
      PIP_CACHE_DIR: /tmp/pip-cache-dir
      PYTHON_VERSION: 3.9.6

    steps:
      # Checks out the repository in the current folder.
      - name: Checks out repository
        uses: actions/checkout@v2

      # Set up the right version of Python
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        id: python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Run pre-commit hooks.
        uses: pre-commit/action@v2.0.3
